Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -22,13 +22,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v2
     - name: Set up JDK 11
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'temurin'
     - name: Build with Gradle
-      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
-      with:
-        arguments: build
+      run: ./gradlew build
+    - name: Run tests
+      run: ./gradlew test
+    - name: Check test results
+      run: |
+        if [ -f build/test-results/test/*.xml ]; then
+          echo "Test results found, checking for failures..."
+          if grep -q 'failure' build/test-results/test/*.xml; then
+            echo "Tests failed. Exiting with status code 1."
+            exit 1
+          else
+            echo "All tests passed."
+          fi
+        else
+          echo "No test results found. Exiting with status code 1."
+          exit 1
+        fi
+    - name: Reject push on test failure
+      if: ${{ failure() }}
+      run: exit 1
+
